// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Starwarsgame.Core.Wookiees.Services;

#nullable disable

namespace Starwarsgame.Core.Wookiees.Services.Migrations
{
    [DbContext(typeof(WookieeContext))]
    [Migration("20230612142533_AddGrade")]
    partial class AddGrade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RoleWookiee", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("WookieesId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "WookieesId");

                    b.HasIndex("WookieesId");

                    b.ToTable("RoleWookiee");
                });

            modelBuilder.Entity("StarwarsGame.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("StarwarsGame.Core.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WookieeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WookieeId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("StarwarsGame.Core.Models.Wookiee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identifiant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbPoils")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wookiee", (string)null);
                });

            modelBuilder.Entity("RoleWookiee", b =>
                {
                    b.HasOne("StarwarsGame.Core.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarwarsGame.Core.Models.Wookiee", null)
                        .WithMany()
                        .HasForeignKey("WookieesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarwarsGame.Core.Models.Weapon", b =>
                {
                    b.HasOne("StarwarsGame.Core.Models.Wookiee", null)
                        .WithMany("Weapons")
                        .HasForeignKey("WookieeId");
                });

            modelBuilder.Entity("StarwarsGame.Core.Models.Wookiee", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
